title: My blog
description: My very nice blog
author: "Jorge Sanz"

theme: minima

base_url: /gh-pages-minima-starter

# Minima social links
twitter_username: xurxosanz
github_username: jsanz
linkedin_username: jsanz
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/ethics.md
  - _pages/jobs.md
  - _pages/archive.md
  - _pages/publications.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
