title: Bib Example
description: "Example site, making a bibtex bibliography on GitHub Pages without jekyll-scholar"
author: "James Weigle"

theme: minima

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/page-1.md
  - _pages/page-2.md
  - _pages/publications.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
